

jwt:
  # 发行者
  name: Hilox
  # 密钥, 经过Base64加密, 自行替换
#  base64Secret: SGlsb3g=
  #jwt中过期时间设置(分)
  jwtExpires: 120
server:
  port: 8093


jwt2:
  #发行者
  subject: com.xinbo
  #密钥
  secret: Zkjvhplv30NMNaqG
  #过期时间
  expire: 3600
  #请求头
  header:
    key: Authorization
    prefix: Bearer
  #放行url
  ignore:
    url: /login,/login2,/generateToken

