server:
  port: 8082
spring:
  application:
    name: cloud-service-oauth
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
jwt:
  secret: javainuse
  get:
    token:
      uri: /authenticate


